### ISSUE TITLE
updates for 2020

### ISSUE THREAD

**Issue by chloeeeeeeeeeeeee** [soyaine/jekyll-theme-diary#6]
Dear soyaine,

first of all, I would like to say THANKS and LOVES for this awesome theme.
this is exactly what I'm looking for!

But sadly since I clone this theme, it seems like I had some problem.

I guess the problem is because I start this calendar in 2020.
can you check this problem for me?

loves, chloeeeeeeeeeeeee

for your reference ; https://chloeeeeeeeeeeeee.github.io/

**Comment by chloeeeeeeeeeeeee** [comment]
I think I fix the problem! thanks and loves again!

**Comment by soyaine** [comment]
@chloeeeeeeeeeeeee Thank u! Feel free to contact me if you have any question while using it.
