### ISSUE TITLE
Cannot find my post at calendar

### ISSUE THREAD

**Issue by jeongchoyi** [soyaine/jekyll-theme-diary#7]
Hello!
I am started to use your theme, and i have 3 basic posts in _posts folder.
(as https://github.com/soyaine/jekyll-theme-diary/tree/master/_posts folder)
And i cannot find my post on calendar when i go to the month it is written.

Even in your Live Demo site (https://soyaine.github.io/jekyll-theme-diary/),
i cannot find that pink dot like your screenshot in your README.md page

How can i / you fix it?
this is my blog, https://iamcho2.github.io/ but i think is same with your demo though.
And this is my repository. https://github.com/iamcho2/iamcho2.github.io
i modified _config.yml, i'm thinking it doesn't matter with calendar.

Thanks!

**Comment by soyaine** [comment]
![image](https://user-images.githubusercontent.com/12845017/93417169-f5951000-f8d9-11ea-98ab-61bbf0479c29.png)
In your blog, the pink dot is located in Sep.16.
The reason why you don't see my posts is the dates of them were the past month.
You can switch the year/month to check it.
And when you already open a page like: https://iamcho2.github.io/2020/09/16/macos-dev-env-setting , you can also see arrows that can be used to switch post on the left or right side of the page.

**Comment by jeongchoyi** [comment]
![image](https://user-images.githubusercontent.com/28949235/93421668-f1262280-f8ec-11ea-89be-ded9fb6dcd6a.png)
Thank you for your reply, but i still cannot see pink dot in my blog.
And in your blog, i switched year/month of course, but i cannot find dots...
I'm using Chrome now,
Do i have to install chrome extensions or sth?

and I can see arrows.

Thanks!

**Comment by soyaine** [comment]
No extension required.
Please open the developer tools and check if there is any error consoled, then copy here.

**Comment by jeongchoyi** [comment]
![image](https://user-images.githubusercontent.com/28949235/93426220-909be300-f8f6-11ea-8f63-42244210fb13.png)
Nope, there is no error printed on console,
and i opened my blog with my another laptop , in Windows, i cannot see pink dot too.

**Comment by soyaine** [comment]
![image](https://user-images.githubusercontent.com/12845017/93428545-40bb1d00-f8f2-11ea-88e3-444776c3b385.png)
Can you see the `<a>` tag of Sep.16 element?

And what's your output in console of `urlJSON`?
```
> console.log(urlJSON)
{2020/9/16: {…}, 2020/8/5: {…}, 2019/8/6: {…}, 2018/12/11: {…}, end: "end"}
2018/12/11: {url: "/2018/12/11/nos-tulit-videt", excerpt: "", index: 1}
2019/8/6: {url: "/2019/08/06/sorores-dicta", excerpt: "", index: 2}
2020/8/5: {url: "/2020/08/05/about", excerpt: "", index: 3}
2020/9/16: {url: "/2020/09/16/macos-dev-env-setting", excerpt: "", index: 4}
end: "end"
__proto__: Object
```

**Comment by jeongchoyi** [comment]
There is no `<a>`tag inside `<li>` tag in mine...
It's like this:
![image](https://user-images.githubusercontent.com/28949235/93430227-4d913e00-f8fd-11ea-9c16-ae84a0fc09f6.png)

and my output of `urlJSON` in console is like this.
![image](https://user-images.githubusercontent.com/28949235/93430132-26d30780-f8fd-11ea-9c33-aef8f1d656a2.png)

**Comment by soyaine** [comment]
Are these above from your local server? Or from this address: https://iamcho2.github.io/ 
It's strange that I can see `<a>` in https://iamcho2.github.io/  , but you can not.

I also found that your repo: https://github.com/iamcho2/iamcho2.github.io is published in `master` branch, I'm not sure does it necessary to build the project before publishing it, because now it( https://iamcho2.github.io/ ) works well on my computer. It seems that GitHub Pages also works on `master`.

In my project, I build them, then move code to the root directory of the `gh-pages` branch, so what you see at  https://soyaine.github.io/jekyll-theme-diary/ is actually in the `gh-pages`  branch.
You can check the code after built at: https://github.com/soyaine/jekyll-theme-diary/tree/gh-pages

Check does this file existed: `/assets/js/calendar.js`,  like: https://iamcho2.github.io/assets/js/calendar.js , or https://soyaine.github.io/jekyll-theme-diary/assets/js/calendar.js . It loads the `urlJSON` to the page.

**Comment by jeongchoyi** [comment]
I did that at my blog address, [https://iamcho2.github.io](https://iamcho2.github.io)

Do you mean it might be related with branch problem?
but your demo blog doesn't work for my Macbooks, my iPhone either...
and i checked at Safari, Microsoft Edge, Chrome but those all didn't work.

And as you can see here, [https://github.com/iamcho2/iamcho2.github.io/tree/master/assets/js](https://github.com/iamcho2/iamcho2.github.io/tree/master/assets/js) 
the file exists.

Also i asked other people whether they can see the pink circle at your blog or not,
everyone answered they cannot. I think your setting or sth is different... or do we have to install sth?

**Comment by soyaine** [comment]
I also tried to open this site on other browsers: Safari, Vivaldi, Firefox, all work.
But I asked someone else, they can not see it too.
Let me check it on the other computer tonight.

**Comment by jeongchoyi** [comment]
Did you find any solution?

**Comment by soyaine** [comment]
Sorry. I forgot about this last night for another thing to do. 
I hope I have time today.

**Comment by soyaine** [comment]
Hi, I tried your site https://iamcho2.github.io/ at my other MacBook, and an Android phone, I can both see the pink `<a>`.
So I need more your info to check why it does not work, so I can help you to debug and fix.

**Comment by jeongchoyi** [comment]
Which info should be given to you?

**Comment by soyaine** [comment]
Do you use Telegram? Could you add me to contact?

**Comment by jeongchoyi** [comment]
I sent you a message, please check it

**Comment by rrotondo** [comment]
Hi, I use a Mac and I tried both on Chrome and Safari but I cannot see posts on calendar. Same behaviour for soyaine and iamcho2 diary.

**Comment by soyaine** [comment]
Fixed in https://github.com/soyaine/jekyll-theme-diary/commit/8fd07df57066498e68edc63d2ea061f16193c46a
