### ISSUE TITLE
Turn this into a template please!

### ISSUE THREAD

**Issue by BravishkaSkytano** [soyaine/jekyll-theme-diary#8]
So, this isn't really an issue but I was wondering if you wouldn't mind turning this into a template? It doesn't alter the theme in any way, it just makes it easier for people to use the theme without forking it or copying it to their computer. It would be a big help for me because most of the stuff I do on GitHub is through mobile since I don't have access to a computer right now.

Anyway, thanks so much for the theme! I too need to be more consistent with my diary and I think using GitHub Pages will definitely help.

**Comment by soyaine** [comment]
@Aspiring-Writer Can you describe in more detail what template you want it to be turned into? or give me some links to the template you mentioned.

**Comment by BravishkaSkytano** [comment]
If you go into the settings for this repository, under the name you should see something like "Use as template". Just check the little checkbox and you're done!

**Comment by soyaine** [comment]
Thank you. I checked it!

**Comment by BravishkaSkytano** [comment]
Yay! Thanks! Now all users have to do is click "Use this template" to clone the entire repo without all the commits
